version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: wginroot
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_SOURCE: postgresql://wginroot:TuvygJ0HULPawBF6DHAu@simple-bank.ctc02sws827c.ap-southeast-2.rds.amazonaws.com:5432/simple_bank
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
