apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: 325274678571.dkr.ecr.ap-southeast-2.amazonaws.com/simplebank:e6d7ffb6dbab982f3487317235a8768673efe304
          # imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-server
